import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import FormInput from "../components/FormInput";
import WordMemoized from "../components/Word";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { asPath } = useRouter();
  const word = trpc.word.getAll.useQuery({ cloud: asPath });

  const words = word.data || [];

  return (
    <>
      <Head>
        <title>Word Cloud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FormInput refetch={word.refetch} path={asPath} />

      <main className="container min-h-screen min-w-full bg-[#191e38] p-2">
        <div className="flex flex-row flex-wrap justify-center text-center">
          {words.map(({ word }, index) => (
            <WordMemoized key={index}>{word}</WordMemoized>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
